// Complete, native shell copy. Order is checked at module load; missing strings
// must never silently display a different language.
const keys = [
  'hint.overview', 'hint.trades', 'hint.calendar', 'hint.reports', 'hint.insight', 'hint.lab', 'hint.drill', 'hint.settings', 'hint.connections', 'hint.import',
  'app.offline', 'top.lastSync', 'prefs.theme.dark', 'prefs.theme.light', 'prefs.scheme.cn', 'prefs.scheme.intl', 'prefs.currency', 'prefs.save', 'prefs.close',
  'state.unavailable', 'state.forbidden', 'connection.available', 'connection.connected', 'connection.unknown', 'connection.readOnly', 'connection.refresh', 'connection.noRoutes',
  'replay.start', 'replay.step', 'replay.back', 'replay.play', 'replay.pause', 'replay.history', 'replay.simulated',
  'insight.edges', 'insight.confirm', 'insight.reject', 'insight.rename', 'insight.evidence', 'insight.limitations', 'insight.unknown', 'action.cancel', 'action.close', 'error.read',
] as const;
type Supplemental = Record<typeof keys[number], string>;
function copy(values: string): Supplemental {
  const entries = values.split('|');
  if (entries.length !== keys.length || entries.some(value => !value.trim())) throw new Error('Incomplete shell translation');
  return Object.fromEntries(keys.map((key, index) => [key, entries[index]])) as Supplemental;
}
export const shellCopy = {
  'zh-TW': copy('今天要關注什麼|已平倉交易與未配對持倉|按日檢視損益|績效、風險、標的與歸因|有證據支持的重複模式|交易計畫、規則庫與回測|真實成交回放與模擬訓練|模型、外掛、診斷與隱私|唯讀同步外部成交與持倉|Excel / CSV / PDF / 截圖|所有資料離線儲存|僅本地帳本|深色|淺色|紅漲綠跌|綠漲紅跌|顯示幣別|套用|關閉|目前環境未開放此服務|目前環境未開放此服務（403）|可設定|已連線|權限未知|唯讀|重新整理|連線服務尚未啟用，離線交易日誌仍可使用。|開始回放|下一根|回退分支|播放|暫停|歷史工作階段|僅為模擬，不會傳送至任何交易通道|優勢資料庫|確認|否決|重新命名|證據|資料限制|未知|取消|關閉|讀取失敗'),
  'ja-JP': copy('今日の注目事項|決済済み取引と未決済建玉|日別損益の確認|成績・リスク・銘柄・要因分析|証拠に基づく反復パターン|売買計画・ルール・バックテスト|実取引の再生と模擬練習|モデル・プラグイン・診断・プライバシー|約定と建玉の読み取り専用同期|Excel / CSV / PDF / スクリーンショット|すべてのデータをオフライン保存|ローカル台帳のみ|ダーク|ライト|上昇は赤・下落は緑|上昇は緑・下落は赤|表示通貨|適用|閉じる|この環境では利用できません|この環境では利用できません（403）|設定可能|接続済み|権限不明|読み取り専用|更新|接続サービスは無効です。オフライン日誌は利用できます。|再生を開始|次の足|巻き戻し分岐|再生|一時停止|セッション履歴|模擬取引のみ。取引所等には送信されません|優位性ライブラリ|確認|却下|名前を変更|根拠|データの制約|不明|キャンセル|閉じる|読み取り失敗'),
  'ko-KR': copy('오늘 확인할 사항|청산 거래와 미결제 포지션|일별 손익 검토|성과·위험·종목·귀인 분석|근거에 기반한 반복 패턴|매매 계획·규칙·백테스트|실제 거래 재생과 모의 연습|모델·플러그인·진단·개인정보|체결과 포지션 읽기 전용 동기화|Excel / CSV / PDF / 스크린샷|모든 데이터 오프라인 저장|로컬 원장만|어둡게|밝게|상승 빨강·하락 초록|상승 초록·하락 빨강|표시 통화|적용|닫기|현재 환경에서 사용할 수 없는 서비스입니다|현재 환경에서 사용할 수 없습니다(403)|설정 가능|연결됨|권한 알 수 없음|읽기 전용|새로 고침|연결 서비스가 꺼져 있습니다. 오프라인 일지는 계속 사용할 수 있습니다.|재생 시작|다음 봉|되감기 분기|재생|일시 정지|세션 기록|모의 거래 전용이며 거래소로 전송되지 않습니다|강점 라이브러리|확인|거부|이름 변경|근거|데이터 제한|알 수 없음|취소|닫기|읽기 실패'),
  'es-ES': copy('Qué revisar hoy|Operaciones cerradas y posiciones abiertas|Revisar resultados por día|Rendimiento, riesgo, activos y atribución|Patrones recurrentes respaldados por pruebas|Planes, reglas y pruebas retrospectivas|Repetición de operaciones reales y simulación|Modelos, complementos, diagnóstico y privacidad|Sincronización de ejecuciones y posiciones de solo lectura|Excel / CSV / PDF / captura de pantalla|Todos los datos se guardan sin conexión|Solo registro local|Oscuro|Claro|Ganancias rojas, pérdidas verdes|Ganancias verdes, pérdidas rojas|Moneda de visualización|Aplicar|Cerrar|Servicio no disponible en este entorno|Servicio no disponible en este entorno (403)|Configurable|Conectado|Permisos desconocidos|Solo lectura|Actualizar|Las conexiones están deshabilitadas. El diario sin conexión sigue disponible.|Iniciar repetición|Siguiente vela|Crear rama al retroceder|Reproducir|Pausar|Historial de sesiones|Solo simulación; no se envía nada a ningún mercado|Biblioteca de ventajas|Confirmar|Rechazar|Cambiar nombre|Pruebas|Limitaciones de datos|Desconocido|Cancelar|Cerrar|Error de lectura'),
  'pt-BR': copy('O que revisar hoje|Operações encerradas e posições abertas|Revisar resultados por dia|Desempenho, risco, ativos e atribuição|Padrões recorrentes com evidências|Planos, regras e testes históricos|Replay de operações reais e simulação|Modelos, plugins, diagnóstico e privacidade|Sincronização de execuções e posições somente leitura|Excel / CSV / PDF / captura de tela|Todos os dados ficam offline|Somente registro local|Escuro|Claro|Ganhos vermelhos, perdas verdes|Ganhos verdes, perdas vermelhas|Moeda de exibição|Aplicar|Fechar|Serviço indisponível neste ambiente|Serviço indisponível neste ambiente (403)|Configurável|Conectado|Permissões desconhecidas|Somente leitura|Atualizar|As conexões estão desativadas. O diário offline continua disponível.|Iniciar replay|Próxima vela|Criar ramificação ao voltar|Reproduzir|Pausar|Histórico de sessões|Somente simulação; nada é enviado a um ambiente de negociação|Biblioteca de vantagens|Confirmar|Rejeitar|Renomear|Evidências|Limitações dos dados|Desconhecido|Cancelar|Fechar|Falha na leitura'),
  'de-DE': copy('Was heute Aufmerksamkeit braucht|Abgeschlossene Trades und offene Positionen|Tägliche Gewinne und Verluste prüfen|Performance, Risiko, Instrumente und Zuordnung|Belegte wiederkehrende Muster|Handelspläne, Regeln und Rücktests|Reale Trades wiedergeben und simulieren|Modelle, Erweiterungen, Diagnose und Datenschutz|Ausführungen und Positionen schreibgeschützt synchronisieren|Excel / CSV / PDF / Bildschirmfoto|Alle Daten werden offline gespeichert|Nur lokales Journal|Dunkel|Hell|Gewinne rot, Verluste grün|Gewinne grün, Verluste rot|Anzeigewährung|Anwenden|Schließen|Dienst in dieser Umgebung nicht verfügbar|Dienst in dieser Umgebung nicht verfügbar (403)|Konfigurierbar|Verbunden|Berechtigungen unbekannt|Nur Lesen|Aktualisieren|Verbindungen sind deaktiviert. Das Offline-Journal bleibt verfügbar.|Replay starten|Nächste Kerze|Rücksprung verzweigen|Abspielen|Anhalten|Sitzungsverlauf|Nur Simulation; keine Übermittlung an einen Handelsplatz|Vorteilsbibliothek|Bestätigen|Ablehnen|Umbenennen|Belege|Datenbeschränkungen|Unbekannt|Abbrechen|Schließen|Lesefehler'),
  'fr-FR': copy('Points à examiner aujourd’hui|Opérations clôturées et positions ouvertes|Examiner les résultats quotidiens|Performance, risque, instruments et attribution|Schémas récurrents étayés par des preuves|Plans, règles et tests historiques|Relecture des opérations réelles et simulation|Modèles, extensions, diagnostic et confidentialité|Synchronisation en lecture seule des exécutions et positions|Excel / CSV / PDF / capture d’écran|Toutes les données restent hors ligne|Registre local uniquement|Sombre|Clair|Gains rouges, pertes vertes|Gains verts, pertes rouges|Devise d’affichage|Appliquer|Fermer|Service indisponible dans cet environnement|Service indisponible dans cet environnement (403)|Configurable|Connecté|Autorisations inconnues|Lecture seule|Actualiser|Les connexions sont désactivées. Le journal hors ligne reste disponible.|Démarrer la relecture|Bougie suivante|Créer une branche de retour|Lire|Suspendre|Historique des sessions|Simulation uniquement ; aucun envoi vers une plateforme de négociation|Bibliothèque d’avantages|Confirmer|Rejeter|Renommer|Preuves|Limites des données|Inconnu|Annuler|Fermer|Échec de lecture'),
};
