"""The storage contract: one interface, one isolation rule.

Why this module exists: the product runs in two places with the same code — a
single-user local machine (SQLite, no dependencies) and the hosted platform
(Postgres, opt-in extra). Callers must not be able to tell them apart, and both
must enforce the same rule, which is the whole point of this file:

    Every tenant-scoped row carries user_id, and every tenant-scoped query
    filters on it. Isolation is enforced by the store, never by the caller.

Because that rule is checked by tests rather than trusted, the rule is stated
once here and repeated literally in each engine's SQL, so a reviewer can read the
predicate in the statement that uses it.

The record dataclasses are the only place rows are normalized. A JSON column is
decoded and a DB column is renamed in exactly one spot, so the two engines cannot
drift in what a trade or a bar means.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, fields
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Protocol, Sequence, runtime_checkable

from smartmoney_cub_harness.schemas import SAFETY_DECLARATION

STORAGE_SCHEMA = "smartmoney_cub_trader_store.v1"

# The DDL lives in schema.sql so both engines create the same tables from one
# text, and so the schema can be read without reading Python.
SCHEMA_FILENAME = "schema.sql"
SCHEMA_PATH = Path(__file__).with_name(SCHEMA_FILENAME)

# Written in the SQL subset both engines accept; see the file header.
DDL_STATEMENT_SEPARATOR = ";"

MODE_LOCAL = "local"
MODE_HOSTED = "hosted"


class StoreError(RuntimeError):
    """The store could not be opened or a row violated the tenant contract."""


def schema_sql() -> str:
    """Return the shared DDL text."""
    return SCHEMA_PATH.read_text(encoding="utf-8")


def iter_statements(ddl: str) -> list[str]:
    """Split a DDL script into executable statements.

    Comment lines are removed before splitting, not after: the shared file
    explains itself in prose, and prose is allowed to contain a semicolon. A
    splitter that ran first would hand the engine a sentence as a statement.
    """
    body = "".join(
        line for line in ddl.splitlines(keepends=True) if not line.strip().startswith("--")
    )
    return [chunk.strip() for chunk in body.split(DDL_STATEMENT_SEPARATOR) if chunk.strip()]


def now_iso() -> str:
    """Local wall-clock timestamp, matching the review store's convention."""
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def new_id(prefix: str) -> str:
    """Generate a row identifier.

    Ids are strings generated by the store rather than by the database, so both
    engines produce the same shape and a row can be addressed before it is
    written.
    """
    return f"{prefix}-{uuid.uuid4().hex[:12]}"


def require_text(value: Any, field: str) -> str:
    text = "" if value is None else str(value).strip()
    if not text:
        raise StoreError(f"{field} must not be empty")
    return text


def optional_text(value: Any) -> str:
    return "" if value is None else str(value).strip()


def require_float(value: Any, field: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise StoreError(f"{field} must be a number, got {value!r}") from exc


def optional_float(value: Any, field: str) -> float | None:
    if value is None or value == "":
        return None
    return require_float(value, field)


def encode_json(value: Any, default: Any) -> str:
    if value is None:
        value = default
    return json.dumps(value, ensure_ascii=False)


def decode_json(value: Any, default: Any) -> Any:
    if value in (None, ""):
        return json.loads(json.dumps(default))
    if isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return json.loads(json.dumps(default))


def safety_envelope(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Attach the execution-ban declaration to a store response.

    One helper, imported from schemas and never redefined, so every store reply
    carries the same string and a response cannot quietly omit it.
    """
    return {**payload, "safety": SAFETY_DECLARATION}


@dataclass(frozen=True)
class Row:
    """Base for the shared record shapes."""

    def to_dict(self) -> dict[str, Any]:
        return {field.name: getattr(self, field.name) for field in fields(self)}


@dataclass(frozen=True)
class UserRecord(Row):
    user_id: str
    tenant_id: str
    display_name: str
    created_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> UserRecord:
        return cls(
            user_id=str(row["user_id"]),
            tenant_id=str(row["tenant_id"]),
            display_name=str(row["display_name"] or ""),
            created_at=str(row["created_at"]),
        )


@dataclass(frozen=True)
class AccountRecord(Row):
    user_id: str
    account_id: str
    name: str
    broker: str
    currency: str
    initial_balance: float
    created_at: str
    updated_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> AccountRecord:
        return cls(
            user_id=str(row["user_id"]),
            account_id=str(row["account_id"]),
            name=str(row["name"] or ""),
            broker=str(row["broker"] or ""),
            currency=str(row["currency"] or "CNY"),
            initial_balance=float(row["initial_balance"] or 0.0),
            created_at=str(row["created_at"]),
            updated_at=str(row["updated_at"]),
        )


@dataclass(frozen=True)
class TradeRecord(Row):
    user_id: str
    trade_id: str
    account_id: str
    symbol: str
    name: str
    side: str
    trade_date: str
    trade_time: str
    price: float
    quantity: float
    fee: float
    thesis: str
    invalidation_price: float | None
    regime: str
    tags: list[str]
    created_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> TradeRecord:
        return cls(
            user_id=str(row["user_id"]),
            trade_id=str(row["trade_id"]),
            account_id=str(row["account_id"] or ""),
            symbol=str(row["symbol"]),
            name=str(row["name"] or ""),
            side=str(row["side"]),
            trade_date=str(row["trade_date"]),
            trade_time=str(row["trade_time"] or ""),
            price=float(row["price"]),
            quantity=float(row["quantity"]),
            fee=float(row["fee"] or 0.0),
            thesis=str(row["thesis"] or ""),
            invalidation_price=(
                None if row["invalidation_price"] is None else float(row["invalidation_price"])
            ),
            regime=str(row["regime"] or ""),
            tags=decode_json(row["tags"], []),
            created_at=str(row["created_at"]),
        )


@dataclass(frozen=True)
class BacktestRunRecord(Row):
    user_id: str
    run_id: str
    strategy_name: str
    symbol: str
    interval: str
    started_at: str
    metrics: dict[str, Any]
    equity_curve: list[Any]
    spec: dict[str, Any]
    created_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> BacktestRunRecord:
        return cls(
            user_id=str(row["user_id"]),
            run_id=str(row["run_id"]),
            strategy_name=str(row["strategy_name"] or ""),
            symbol=str(row["symbol"] or ""),
            interval=str(row["bar_interval"] or ""),
            started_at=str(row["started_at"] or ""),
            metrics=decode_json(row["metrics"], {}),
            equity_curve=decode_json(row["equity_curve"], []),
            spec=decode_json(row["spec"], {}),
            created_at=str(row["created_at"]),
        )


@dataclass(frozen=True)
class BarRecord(Row):
    """One OHLCV bar, keyed per tenant.

    The column is named bar_interval because interval is a reserved word in
    several SQL dialects, but the row is exposed as interval so it matches the
    market-data Bar shape the rest of the product uses.
    """

    user_id: str
    symbol: str
    interval: str
    open_time: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    provider: str
    fetched_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> BarRecord:
        return cls(
            user_id=str(row["user_id"]),
            symbol=str(row["symbol"]),
            interval=str(row["bar_interval"]),
            open_time=str(row["open_time"]),
            open=float(row["open"]),
            high=float(row["high"]),
            low=float(row["low"]),
            close=float(row["close"]),
            volume=float(row["volume"] or 0.0),
            provider=str(row["provider"] or ""),
            fetched_at=str(row["fetched_at"] or ""),
        )


@dataclass(frozen=True)
class AuditRecord(Row):
    user_id: str
    audit_id: str
    action: str
    record_id: str
    detail: dict[str, Any]
    created_at: str

    @classmethod
    def from_row(cls, row: Mapping[str, Any]) -> AuditRecord:
        return cls(
            user_id=str(row["user_id"]),
            audit_id=str(row["audit_id"]),
            action=str(row["action"]),
            record_id=str(row["record_id"] or ""),
            detail=decode_json(row["detail"], {}),
            created_at=str(row["created_at"]),
        )


@runtime_checkable
class TenantStore(Protocol):
    """One storage interface, two engines, one isolation rule.

    Every method that touches rows takes user_id first and scopes its SQL to it.
    A caller cannot ask for another tenant's rows because there is no argument
    that would express that request.

    get_user returns None when the user does not exist, while the list methods
    return an empty list: a missing tenant and a tenant with no rows are the same
    answer to a scoped query, and neither leaks the other's data.
    """

    def migrate(self) -> dict[str, Any]:
        """Create or update the schema. Safe to call repeatedly."""

    def create_user(
        self, user_id: str, *, tenant_id: str | None = None, display_name: str = ""
    ) -> dict[str, Any]:
        """Create the tenant row, or update its display fields if it exists."""

    def get_user(self, user_id: str) -> dict[str, Any] | None:
        """Return one tenant row, or None."""

    def list_trades(
        self,
        user_id: str,
        *,
        account_id: str | None = None,
        symbol: str | None = None,
        start: str | None = None,
        end: str | None = None,
        limit: int = 500,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        """Return this tenant's trades, newest filterable by account/date."""

    def insert_trades(self, user_id: str, rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
        """Append trades for this tenant. Refuses an unknown user_id."""

    def list_accounts(self, user_id: str) -> list[dict[str, Any]]:
        """Return this tenant's accounts."""

    def upsert_account(self, user_id: str, account: Mapping[str, Any]) -> dict[str, Any]:
        """Create or update one account, scoped to this tenant."""

    def save_backtest_run(self, user_id: str, run: Mapping[str, Any]) -> dict[str, Any]:
        """Persist one backtest run and its metrics, scoped to this tenant."""

    def list_backtest_runs(self, user_id: str, *, limit: int = 100) -> list[dict[str, Any]]:
        """Return this tenant's saved backtest runs, newest first."""

    def save_bars(self, user_id: str, bars: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
        """Upsert bars into this tenant's cache."""

    def load_bars(
        self,
        user_id: str,
        *,
        symbol: str,
        interval: str,
        start: str | None = None,
        end: str | None = None,
        limit: int = 500,
    ) -> list[dict[str, Any]]:
        """Return this tenant's cached bars for one symbol and interval."""

    def audit(
        self,
        user_id: str,
        action: str,
        *,
        record_id: str | None = None,
        detail: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Append one tenant-scoped audit entry."""

    def update_trade_names(
        self, user_id: str, symbol_names: Mapping[str, str], *, force: bool = False
    ) -> int:
        """Update trade names for matching symbols."""

    def save_symbol_metadata(self, metadata: Sequence[Mapping[str, Any]]) -> None:
        """Save symbol metadata into cache."""

    def load_symbol_metadata(
        self, symbols: Sequence[str] | None = None
    ) -> dict[str, dict[str, Any]]:
        """Load cached symbol names and ST status."""
