-- Shared tenant schema for the trader product store.
--
-- Why one file serves two engines: the local store is SQLite and the hosted
-- store is Postgres, and the tenant isolation rule is only real if both create
-- the same tables. The DDL below is written in the intersection of the two
-- dialects, which means it deliberately avoids engine-specific types and
-- constraints:
--
--   * No SERIAL / AUTOINCREMENT: primary keys are text ids generated by the
--     store, so both engines insert the same value.
--   * No CHECK constraints: string domains (side, bar_interval) are validated in
--     the store, so the two engines cannot disagree about what is legal.
--   * No TIMESTAMP: timestamps are ISO-8601 UTC text, matching the review store.
--   * DOUBLE PRECISION, INTEGER, and TEXT all exist in both engines.
--   * ON CONFLICT ... DO UPDATE is supported by SQLite 3.24+ and Postgres 15+,
--     and every upsert below carries a user_id term so a cross-tenant write
--     cannot land through the conflict path.
--
-- Two tables are deliberately tenant-scoped with user_id leading their primary
-- key: accounts and audit_log are addressed by id within a tenant, never
-- globally.
--
-- Every tenant-scoped row carries user_id, and every tenant-scoped query filters
-- on it. Isolation is enforced by the store, never by the caller.

-- The tenant itself. A local install has exactly one row; a hosted tenant is one
-- alphatech platform identity.
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Broker or prop-firm accounts inside a tenant. account_id is unique per tenant,
-- which is why the key is the pair rather than the id alone.
CREATE TABLE IF NOT EXISTS accounts (
    user_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    broker TEXT NOT NULL DEFAULT '',
    currency TEXT NOT NULL DEFAULT 'CNY',
    initial_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, account_id)
);

CREATE INDEX IF NOT EXISTS accounts_tenant_name
    ON accounts (user_id, name);

-- Executions the trader imported. This is the journal the product is built on.
CREATE TABLE IF NOT EXISTS trades (
    user_id TEXT NOT NULL,
    trade_id TEXT NOT NULL,
    account_id TEXT NOT NULL DEFAULT '',
    symbol TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    side TEXT NOT NULL,
    trade_date TEXT NOT NULL,
    trade_time TEXT NOT NULL DEFAULT '',
    price DOUBLE PRECISION NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    thesis TEXT NOT NULL DEFAULT '',
    invalidation_price DOUBLE PRECISION,
    regime TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, trade_id)
);

CREATE INDEX IF NOT EXISTS trades_tenant_date
    ON trades (user_id, trade_date, trade_time);

CREATE INDEX IF NOT EXISTS trades_tenant_symbol
    ON trades (user_id, symbol);

-- Saved backtest runs. Strategy spec and results are stored as JSON text so the
-- DSL can grow without a migration, matching how the review store keeps
-- payloads.
CREATE TABLE IF NOT EXISTS backtest_runs (
    user_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    strategy_name TEXT NOT NULL DEFAULT '',
    symbol TEXT NOT NULL DEFAULT '',
    bar_interval TEXT NOT NULL DEFAULT '',
    started_at TEXT NOT NULL DEFAULT '',
    metrics TEXT NOT NULL DEFAULT '{}',
    equity_curve TEXT NOT NULL DEFAULT '[]',
    spec TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, run_id)
);

CREATE INDEX IF NOT EXISTS backtest_runs_tenant_created
    ON backtest_runs (user_id, created_at);

-- Cached market bars. The column is bar_interval because interval is reserved in
-- several dialects; the row is exposed as interval. The primary key makes the
-- cache an upsert target, so re-fetching a series corrects a bar instead of
-- duplicating it.
CREATE TABLE IF NOT EXISTS market_bars (
    user_id TEXT NOT NULL,
    symbol TEXT NOT NULL,
    bar_interval TEXT NOT NULL,
    open_time TEXT NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION NOT NULL DEFAULT 0,
    provider TEXT NOT NULL DEFAULT '',
    fetched_at TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (user_id, symbol, bar_interval, open_time)
);

-- The tenant-scoped audit trail: what this user's store changed, and when.
CREATE TABLE IF NOT EXISTS audit_log (
    user_id TEXT NOT NULL,
    audit_id TEXT NOT NULL,
    action TEXT NOT NULL,
    record_id TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, audit_id)
);

CREATE INDEX IF NOT EXISTS audit_log_tenant_created
    ON audit_log (user_id, created_at);
