from __future__ import annotations

from smartmoney_cub_harness.plugins.envelope import (
    EvidenceEnvelopeError,
    build_evidence_envelope,
    validate_evidence_envelope,
)
from smartmoney_cub_harness.plugins.lifecycle import (
    Disposer,
    EffectScope,
    PluginState,
    PluginInstance,
)
from smartmoney_cub_harness.plugins.manifest import (
    PLUGIN_MANIFEST_SCHEMA,
    PluginManifest,
    ManifestError,
    parse_manifest,
    validate_manifest,
)
from smartmoney_cub_harness.plugins.profiles import BUILTIN_PROFILES, Bundle, Patch, Profile
from smartmoney_cub_harness.plugins.registry import PluginRegistry, PluginStateStore
from smartmoney_cub_harness.plugins.runtime import (
    PLUGIN_ENTRY_POINT_GROUP,
    PluginExecutionError,
    PluginHost,
    PluginPermissionError,
    PluginRuntime,
    SubprocessProvider,
    discover_installed_entry_points,
    discover_manifest_paths,
)
from smartmoney_cub_harness.plugins.services import (
    SERVICE_DEFINITIONS,
    BaseConsumer,
    BaseProvider,
    CapabilityConflictError,
    MissingDependencyError,
    ServiceConsumer,
    ServiceDefinition,
    ServiceProvider,
    ServiceRegistry,
)
from smartmoney_cub_harness.plugins.types import (
    PLUGIN_API_VERSION,
    CapabilityName,
    PluginKind,
    TrustLevel,
)
from smartmoney_cub_harness.plugins.curated_catalog import (
    CURATED_CATALOG_SCHEMA,
    CURATED_FINANCE_PLUGINS,
    CURATED_MANIFEST_SCHEMA,
    CuratedFinancePluginCatalog,
    CuratedFinancePluginDescriptor,
    CuratedManifestError,
    curated_catalog_payload,
    parse_curated_manifest,
    validate_curated_manifest,
)
from smartmoney_cub_harness.plugins.cordis_adapters import (
    CordisAdapterResult,
    CordisBoundaryError,
    CordisReviewRequest,
    EvaluatorMemoryChallengerToyAdapter,
    TradingAgentsMultiRoleToyAdapter,
    build_toy_review_request,
    request_challenger_promotion,
)

__all__ = [
    "BUILTIN_PROFILES",
    "BaseConsumer",
    "BaseProvider",
    "Bundle",
    "CapabilityName",
    "CapabilityConflictError",
    "Disposer",
    "EffectScope",
    "EvidenceEnvelopeError",
    "ManifestError",
    "MissingDependencyError",
    "PLUGIN_API_VERSION",
    "PLUGIN_ENTRY_POINT_GROUP",
    "PLUGIN_MANIFEST_SCHEMA",
    "Patch",
    "PluginInstance",
    "PluginExecutionError",
    "PluginHost",
    "PluginKind",
    "PluginManifest",
    "PluginPermissionError",
    "PluginRegistry",
    "PluginRuntime",
    "PluginState",
    "PluginStateStore",
    "Profile",
    "SERVICE_DEFINITIONS",
    "ServiceConsumer",
    "ServiceDefinition",
    "ServiceProvider",
    "ServiceRegistry",
    "SubprocessProvider",
    "TrustLevel",
    "CURATED_CATALOG_SCHEMA",
    "CURATED_FINANCE_PLUGINS",
    "CURATED_MANIFEST_SCHEMA",
    "CuratedFinancePluginCatalog",
    "CuratedFinancePluginDescriptor",
    "CuratedManifestError",
    "curated_catalog_payload",
    "parse_curated_manifest",
    "validate_curated_manifest",
    "CordisAdapterResult",
    "CordisBoundaryError",
    "CordisReviewRequest",
    "EvaluatorMemoryChallengerToyAdapter",
    "TradingAgentsMultiRoleToyAdapter",
    "build_toy_review_request",
    "request_challenger_promotion",
    "build_evidence_envelope",
    "discover_installed_entry_points",
    "discover_manifest_paths",
    "parse_manifest",
    "validate_evidence_envelope",
    "validate_manifest",
]
